// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q      = new(Query)
	Domain *domain
	File   *file
	Link   *link
	Path   *path
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Domain = &Q.Domain
	File = &Q.File
	Link = &Q.Link
	Path = &Q.Path
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:     db,
		Domain: newDomain(db, opts...),
		File:   newFile(db, opts...),
		Link:   newLink(db, opts...),
		Path:   newPath(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Domain domain
	File   file
	Link   link
	Path   path
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Domain: q.Domain.clone(db),
		File:   q.File.clone(db),
		Link:   q.Link.clone(db),
		Path:   q.Path.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Domain: q.Domain.replaceDB(db),
		File:   q.File.replaceDB(db),
		Link:   q.Link.replaceDB(db),
		Path:   q.Path.replaceDB(db),
	}
}

type queryCtx struct {
	Domain IDomainDo
	File   IFileDo
	Link   ILinkDo
	Path   IPathDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Domain: q.Domain.WithContext(ctx),
		File:   q.File.WithContext(ctx),
		Link:   q.Link.WithContext(ctx),
		Path:   q.Path.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
