// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomain = "domains"

// Domain mapped from table <domains>
type Domain struct {
	ID        int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:varchar(45);not null" json:"name"`
	URL       string    `gorm:"column:url;type:varchar(45);not null" json:"url"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
}

// TableName Domain's table name
func (*Domain) TableName() string {
	return TableNameDomain
}
