// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLink = "links"

// Link mapped from table <links>
type Link struct {
	ID        int32     `gorm:"column:ID;type:int unsigned;primaryKey;autoIncrement:true" json:"ID"`
	Name      string    `gorm:"column:name;type:varchar(45);not null" json:"name"`
	URL       string    `gorm:"column:url;type:varchar(45);not null" json:"url"`
	PathsID   int32     `gorm:"column:paths_ID;type:int;not null" json:"paths_ID"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
}

// TableName Link's table name
func (*Link) TableName() string {
	return TableNameLink
}
