// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePath = "paths"

// Path mapped from table <paths>
type Path struct {
	ID        int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:varchar(45);not null" json:"name"`
	URL       string    `gorm:"column:url;type:varchar(45);not null" json:"url"`
	ParentID  int32     `gorm:"column:parent_id;type:int;not null" json:"parent_id"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
}

// TableName Path's table name
func (*Path) TableName() string {
	return TableNamePath
}
